# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 01:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, null=True)),
                ('authors', models.CharField(max_length=128, null=True)),
                ('publisher', models.CharField(max_length=256, null=True)),
                ('publishedDate', models.CharField(max_length=256, null=True)),
                ('description', models.TextField(max_length=4096, null=True)),
                ('isbn', models.CharField(max_length=40, null=True)),
                ('averageRating', models.FloatField(max_length=2)),
                ('thumbnail', models.URLField(max_length=2000, null=True)),
                ('textSnippet', models.TextField(max_length=2000, null=True)),
                ('pageCount', models.IntegerField()),
                ('pageViews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm.Book')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.CharField(blank=True, max_length=2000)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('favouriteBook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookworm.Book')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
